library(magrittr)
library(laGP)

load("data/genotype_data/janno_final.RData")
load("data/parameter_exploration/variogram/estimated_nuggets.RData")
nugget_derived <- as.numeric(readLines("data/parameter_exploration/variogram/nuggets.txt")[1])

mle_out <- mobest::laGP_mle_sequence_isotropic_fixed_g(
  independent = mobest::create_spatpos(
    id = janno_final$Poseidon_ID,
    x = janno_final$x / 1000,
    y = janno_final$y / 1000,
    z = janno_final$Date_BC_AD_Median_Derived
  ),
  dependent = mobest::create_obs(
    C1 = janno_final$C1,
    C2 = janno_final$C2
  ),
  iterations = 5,
  g = nugget_derived,
  space_time_scaling_factor_sequence = seq(0.1, 2.0, 0.1)
)

save(mle_out, file = "data/parameter_exploration/mle/mle_out.RData")



