library(magrittr)
library(laGP)

load("data/genotype_data/janno_final.RData")
load("data/parameter_exploration/variogram/estimated_nuggets.RData")

mle_iso <- mobest::laGP_mle_sequence_isotropic_fixed_g(
  independent = mobest::create_spatpos(
    id = janno_final$Poseidon_ID,
    x = janno_final$x / 1000,
    y = janno_final$y / 1000,
    z = janno_final$Date_BC_AD_Median_Derived
  ),
  dependent = mobest::create_obs(
    C1_mds_u = janno_final$C1_mds_u,
    C2_mds_u = janno_final$C2_mds_u,
    C3_mds_u = janno_final$C3_mds_u
  ),
  iterations = 5,
  g = tibble::deframe(estimated_nuggets[,c("dependent_var_id", "nugget")]),
  space_time_scaling_factor_sequence = seq(0.1, 2.0, 0.1)
)

save(mle_iso, file = "data/parameter_exploration/mle_iso.RData")
